
proxy_cache_path /tmp/nginx_cache 
    levels=1:2 
    keys_zone=stats_cache:10m 
    max_size=100m 
    inactive=60m;

upstream backend_block {
    server api-a:3000;
    server api-b:3000;
}

server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/stats {
        proxy_pass http://backend_block/stats/;
        
        # proxy_cache stats_cache;
        # proxy_cache_valid 200 5s;
        
        add_header X-Cache-Status $upstream_cache_status;
    }

    location /api/ {
        proxy_pass http://backend_block/;
    }
}