
proxy_cache_path /tmp/nginx_cache 
    levels=1:2 
    keys_zone=stats_cache:10m 
    max_size=100m 
    inactive=60m;

server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/stats {
        proxy_pass http://backend:3000/stats/;
        
        proxy_cache stats_cache;
        proxy_cache_valid 200 30s;
        
        add_header X-Cache-Status $upstream_cache_status;
    }

    location /api/ {
        proxy_pass http://backend:3000/;
    }
}