upstream backend_block {
    server backend_1:3000;
    server backend_2:3000;
}

server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/stats {
        proxy_pass http://backend_block/stats/;        
        add_header X-Cache-Status $upstream_cache_status;
    }

    location /api/ {
        proxy_pass http://backend_block/;
    }
}
